name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0.0"
        
    - name: Get swift version
      run: swift --version
      
    - name: Get swift version in macOS
      if: runner.os == 'macOS'
      run: xcrun --toolchain ${{ env.TOOLCHAINS }} swift --version
        
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v 