name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["6.0.0"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
        
    - name: Get Swift version
      run: swift --version
        
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v 